### ISSUE TITLE
Long comments.

### ISSUE THREAD

**Issue by gSe7eN** [djohnsonbaugh/vscodemq2macro#3]
|** Long comments
Like this example
Would be great to have in this extension **|

Any chance for multiline comments? =)

Oh, that's weird. We do have long comments, but this one fails for some reason.

`    |**
    /shift /itemnotify "${FindItem[Alaran Cantrip].Name}" leftmouseup
    /call Give
    /shift /itemnotify "${FindItem[Alaran Cantrip].Name}" leftmouseup
    /call Give
    /shift /itemnotify "${FindItem[Alaran Cantrip].Name}" leftmouseup
    /call Give
    /shift /itemnotify "${FindItem[Alaran Cantrip].Name}" leftmouseup
    /call Give
    /shift /itemnotify "${FindItem[Alaran Cantrip].Name}" leftmouseup
    /call Give
    /shift /itemnotify "${FindItem[dreadmote].Name}" leftmouseup
    /call Give
    /shift /itemnotify "${FindItem[dreadmote].Name}" leftmouseup
    /call Give
    /shift /itemnotify "${FindItem[dreadmote].Name}" leftmouseup
    /call Give
    || Next 8
    /shift /itemnotify "${FindItem[dreadmote].Name}" leftmouseup
    /call Give
    /shift /itemnotify "${FindItem[dreadmote].Name}" leftmouseup
    /call Give
    /shift /itemnotify "${FindItem[essence of life].Name}" leftmouseup
    /call Give
    /shift /itemnotify "${FindItem[essence of life].Name}" leftmouseup
    /call Give
    /shift /itemnotify "${FindItem[essence of life].Name}" leftmouseup
    /call Give
    /shift /itemnotify "${FindItem[essence of life].Name}" leftmouseup
    /call Give
    /shift /itemnotify "${FindItem[agony].Name}" leftmouseup
    /call Give
    /shift /itemnotify "${FindItem[bite].Name}" leftmouseup
    
    /call Give
    **|`

**Comment by djohnsonbaugh** [comment]
Looks like a bug, will look tonight.

**Comment by djohnsonbaugh** [comment]
fixed, should be available on marketplace now.
